import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers";
import TopNav from "@/components/Navbar/TopNav";
import { auth } from "@/auth";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "NextMatch",
  description: "Generated by create next app",
};

export default async  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  const userId = session?.user?.id ||null
  const profileComplete = session?.user.profileComplete as boolean

  return (
    <html lang="en">
      <body>
        <Providers userId = {userId} profileComplete={profileComplete}>
          <TopNav />
          <main className='min-h-screen bg-gradient-to-br from-secondary-50 to-purple-100 text-gray-800 p-10'>
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}